apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wiki
  name: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      serviceAccount: tekton
      containers:
      - image: docker.io/piyushgarg/wiki
        name: wiki
        ports:
        - containerPort: 8080
